### PR TITLE
WEB 451 - Fix /artist page scrolling on mobile

### PR DESCRIPTION
**Pull request by joesobo**

### CODE REVIEW

**Comment by cindyssun5** [comment]
@joesobo There's been some updates to master, so if you can rebase from master, we can review your PR

**Comment by joesobo** [comment]
> @joesobo There's been some updates to master, so if you can rebase from master, we can review your PR

Branch has been rebased

**Comment by joannerd** [comment]
Looks good on all mobile devices except iPhone SE! Can we add the same bottom margin for SE?

### Non-SE
Image from iOS


### SE
Screen Shot 2020-11-20 at 1 22 06 PM

**Comment by joesobo** [comment]
> Looks good on all mobile devices except iPhone SE! Can we add the same bottom margin for SE?
> 


Updated for iPhone SE. Looked good on my emulator

**Review by joannerd — APPROVED** [review]

**Review by cindyssun5 — APPROVED** [review]

**Pull request merged**
